// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Connection struct {
	ID           int64
	Connectionid string
	Accountid    pgtype.Int8
	Userid       pgtype.Int8
	Createdate   pgtype.Timestamp
	Lastupdated  pgtype.Timestamp
	Recordstatus string
	Active       string
	Connected    pgtype.Text
	Disconnected pgtype.Text
	Userdata     pgtype.Text
	Accountdata  pgtype.Text
	Authmenu     pgtype.Text
	Authkeys     pgtype.Text
	Authgroups   pgtype.Text
	Sites        pgtype.Text
	Clients      pgtype.Text
}

type Site struct {
	Accountid         int64
	Siteid            int64
	Sitename          string
	Createdate        pgtype.Timestamp
	Lastupdated       pgtype.Timestamp
	Recordstatus      string
	Active            string
	Des               pgtype.Text
	Description       pgtype.Text
	Operateby         pgtype.Text
	Logo              pgtype.Text
	Rulesdocuments    pgtype.Text
	Servicesamenities pgtype.Text
	Type              pgtype.Text
	Email             pgtype.Text
	Phone             pgtype.Text
	Address           pgtype.Text
	Website           pgtype.Text
	Geolocation       pgtype.Text
}

type User struct {
	Accountid      int64
	Userid         int64
	Createdate     pgtype.Timestamp
	Lastupdated    pgtype.Timestamp
	Recordstatus   string
	Active         string
	Identification pgtype.Text
	Password       pgtype.Text
	Companyname    pgtype.Text
	Firstname      pgtype.Text
	Lastname       pgtype.Text
	Email          pgtype.Text
	Phone          pgtype.Text
	Emergencyphone pgtype.Text
	I18n           pgtype.Text
	Address        pgtype.Text
	Authmenu       pgtype.Text
	Authkeys       pgtype.Text
	Authgroups     pgtype.Text
	Sites          pgtype.Text
	Clients        pgtype.Text
}
