// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package sqlc

import (
	"context"
)

const getAuthor = `-- name: GetAuthor :one
SELECT accountid, userid, createdate, lastupdated, recordstatus, active, identification, password, companyname, firstname, lastname, email, phone, emergencyphone, i18n, address, authmenu, authkeys, authgroups, sites, clients FROM Users
`

func (q *Queries) GetAuthor(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, getAuthor)
	var i User
	err := row.Scan(
		&i.Accountid,
		&i.Userid,
		&i.Createdate,
		&i.Lastupdated,
		&i.Recordstatus,
		&i.Active,
		&i.Identification,
		&i.Password,
		&i.Companyname,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Phone,
		&i.Emergencyphone,
		&i.I18n,
		&i.Address,
		&i.Authmenu,
		&i.Authkeys,
		&i.Authgroups,
		&i.Sites,
		&i.Clients,
	)
	return i, err
}
