CREATE TABLE Users (
    accountId BIGINT NOT NULL,
    userId BIGSERIAL NOT NULL,
    createDate TIMESTAMP NOT NULL,
    lastUpdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recordStatus VARCHAR(20) DEFAULT 'app.status.Active' NOT NULL,
    active VARCHAR(20) DEFAULT 'app.status.Active' NOT NULL,
    identification VARCHAR(50),
    password VARCHAR(50),
    companyName VARCHAR(50),
    firstName VARCHAR(50),
    lastName VARCHAR(50),
    email VARCHAR(50),
    phone VARCHAR(50),
    emergencyPhone VARCHAR(50),
    i18n VARCHAR(50),
    address VARCHAR(200),
    authMenu TEXT DEFAULT '[]',
    authKeys TEXT DEFAULT '[]',
    authGroups TEXT DEFAULT '[]',
    Sites TEXT DEFAULT '[]',
    Clients TEXT DEFAULT '[]',
    PRIMARY KEY (userId)
);

CREATE TABLE Connections (
    id BIGSERIAL NOT NULL,
    connectionId VARCHAR(50) NOT NULL,
    accountId BIGINT,
    userId BIGINT,
    createDate TIMESTAMP NOT NULL,
    lastUpdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recordStatus VARCHAR(20) DEFAULT 'app.status.Active' NOT NULL,
    active VARCHAR(20) DEFAULT 'app.status.Active' NOT NULL,
    connected VARCHAR(50),
    disconnected VARCHAR(50),
    userData TEXT DEFAULT '{}',
    accountData TEXT DEFAULT '{}',
    authMenu TEXT DEFAULT '[]',
    authKeys TEXT DEFAULT '[]',
    authGroups TEXT DEFAULT '[]',
    Sites TEXT DEFAULT '[]',
    Clients TEXT DEFAULT '[]',
    PRIMARY KEY (id)
);

CREATE TABLE Sites (
    accountId BIGINT NOT NULL,
    siteId BIGSERIAL NOT NULL,
    siteName VARCHAR(50) NOT NULL,
    createDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recordStatus VARCHAR(20) DEFAULT 'app.status.Active' NOT NULL,
    active VARCHAR(20) DEFAULT 'app.status.Active' NOT NULL,
    des VARCHAR(200),
    description VARCHAR,
    operateBy VARCHAR(50),
    logo VARCHAR,
    rulesDocuments TEXT DEFAULT '{}',
    servicesAmenities TEXT DEFAULT '{}',
    type VARCHAR(50) DEFAULT 'Yard',
    email VARCHAR(50),
    phone VARCHAR(50),
    address VARCHAR(200),
    website VARCHAR(200),
    geolocation VARCHAR(200),
    PRIMARY KEY (siteId)
);
